# Generated by Django 5.2 on 2025-04-13 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('event_price', models.CharField()),
                ('for_whom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('teacher_bio', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teacher_images/')),
                ('social_akk', models.FileField(upload_to='social')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs_app.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('course_image', models.FileField(upload_to='course_image')),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.SmallIntegerField()),
                ('category', models.ManyToManyField(to='kurs_app.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='kurs_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='for_video')),
                ('students_graduated', models.IntegerField()),
                ('completed_courses', models.IntegerField()),
                ('qualified_tutors', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('studying_process', models.TextField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs_app.courses')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs_app.teacher')),
            ],
        ),
    ]
