# Generated by Django 5.2 on 2025-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='social_akk',
            field=models.URLField(),
        ),
    ]
